config/routes.rb
Salaverde::Application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get 'about'   => 'static_pages#about'
    resources :salas
  end

  root 'salas#index'
end

app/models/sala.rb
class Sala < ActiveRecord::Base
  geocoded_by :lugar_festejo
  after_validation :geocode

  validates :nombre,
            :apellido,
            :cumple,
            :email, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale
  
private 

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end
  
  def default_url_options(options = {})
    {locale: I18n.locale}
  end
end

app/controllers/salas_controller.rb
class SalasController < ApplicationController
  before_action :set_sala, only: [:show, :edit, :update, :destroy]

  def index
    @salas = Sala.paginate(page: params[:page]).per_page(8).order(:fecha_festejo)
  end

  def show
    @hash = Gmaps4rails.build_markers(@sala) do |user, marker|
      marker.lat @sala.latitude
      marker.lng @sala.longitude
    end
  end

  def new
    @sala = Sala.new
  end

  def edit
  end

  def create
    @sala = Sala.new(sala_params)
    set_default_location
    respond_to do |format|
      if @sala.save
        format.html { redirect_to @sala, notice: 'Registro agregado.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    set_default_location
    respond_to do |format|
      if @sala.update(sala_params)
        format.html { redirect_to @sala, notice: 'Registro modificado.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @sala.destroy
    respond_to do |format|
      format.html { redirect_to salas_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sala
      @sala = Sala.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sala_params
      params.fetch(:sala, {}).permit(:nombre, :apellido, :cumple, :email,
                                   :fecha_festejo, :lugar_festejo)
    end

    def set_default_location
      unless params[:lugar_festejo].present?
        @sala.latitude = '-34.603229'
        @sala.longitude = '-58.381842'
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".footer_by" %>
  </small>
  <nav>
	<ul>
	  <li><%= link_to (t ".footer_about"), about_path %></li>
	  <li><a href="https://github.com/gpessacq/">Tigerstripes</a></li>
	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Sala Verde", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to (t ".top"), root_path %></li>
        </ul>
      	<ul class="nav navbar-nav navbar-right">
      	  <li class="navbar-text"><%= t ".language" %></li>
      	  <li class="active"><%= link_to_unless_current "English", locale: "en" %></li>
      	  <li class="active"><%= link_to_unless_current "Español", locale: "es" %></li>
      	</ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sala verde</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/salas/_form.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="well bs-component">
			<%= form_for @sala, html: { class: "form-horizontal", id: "form-horizontal" } do |f| %>
			  <fieldset>
				  <% if @sala.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@sala.errors.count, "error") %> prohibited this sala from being saved:</h2>
				      <ul>
					      <% @sala.errors.full_messages.each do |msg| %>
					        <li>
									  <%= msg %>
									</li>
					      <% end %>
				      </ul>
				    </div>
				  <% end %>
			  	<div class="form-group">
			      <div class="field">
					    <%= f.label :nombre %><br>
					    <%= f.text_field :nombre, :class => 'form-control', :id => 'inputSmall' %>
				  	</div>
					</div>
					<div class="form-group">
					  <div class="field">
					    <%= f.label :apellido %><br>
					    <%= f.text_field :apellido, :class => 'form-control', :id => 'inputSmall' %>
					  </div>
					</div>
					<div class="form-group">
					  <div class="field">
					    <%= f.label :cumple %><br>
					    <%= f.date_select :cumple,
					                      order: [:day, :month, :year],
					                      with_css_classes: true %>
					  </div>
					</div>
					<div class="form-group">
					  <div class="field">
					    <%= f.label :email %><br>
					    <%= f.text_field :email, :class => 'form-control', :id => 'inputSmall' %>
					  </div>
					</div>
					<div class="form-group">
					  <div class="field">
					    <%= f.label :fecha_festejo %><br>
					    <%= f.datetime_select :fecha_festejo,
					                          :minute_step => 15,
					                          :order => [:hour, :day, :month, :year],
					                          with_css_classes: true %>
					  </div>
					</div>
					<div class="form-group">
					  <div class="field">
					    <%= f.label :lugar_festejo %><br>
					    <%= f.text_field :lugar_festejo, size: 40, :placeholder => "Dirección, Ciudad, País", :class => 'form-control', :id => 'inputSmall'  %>
					  </div>
					</div>
					<br>
				  <div class="form-group">
					  <div class="col-lg-10 col-lg-offset-4">
					    <%= f.button (t ".save"), :class => 'btn btn-default' %>
					  </div>
				  </div>
			  </fieldset>
			 <% end %>
		</div>
	</div>
</div>

app/views/salas/_maps.html.erb
<script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

app/views/salas/edit.html.erb
<h1><%= t ".title" %></h1>

<%= render 'form' %>

<%= link_to (t ".show"), @sala %> |
<%= link_to (t ".back"), salas_path %>

app/views/salas/index.html.erb
<h1><%= t ".title" %></h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= Sala.human_attribute_name(:nombre) %></th>
      <th><%= Sala.human_attribute_name(:apellido) %></th>
      <th><%= Sala.human_attribute_name(:cumple) %></th>
      <th><%= Sala.human_attribute_name(:email) %></th>
      <th><%= Sala.human_attribute_name(:fecha_festejo) %></th>
      <th><%= Sala.human_attribute_name(:lugar_festejo) %></th>
      <th><%= t ".actions" %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  	<%= will_paginate %>
    <% @salas.each do |sala| %>
      <tr>
        <td><%= sala.nombre.capitalize %></td>
        <td><%= sala.apellido.capitalize %></td>
        <td><%= l(sala.cumple, format: :long) %></td>
        <td><%= sala.email %></td>
        <td><%= l(sala.fecha_festejo, format: :longer) %></td>
        <td><%= sala.lugar_festejo %></td>
        <td><%= link_to (t ".show"), sala, class: "btn btn-info btn-sm" %></td>
        <td><%= link_to (t ".edit"), edit_sala_path(sala), class: "btn btn-warning btn-sm" %></td>
        <td><%= link_to (t ".delete"), sala, method: :delete,
                data: { confirm: (t ".confirm") },
                class: "btn btn-danger btn-sm" %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate  %>
<br>

<%= link_to (t ".add"), new_sala_path %>

app/views/salas/new.html.erb
<h1><%= t ".title" %></h1>

<%= render 'form' %>

<%= link_to (t ".back"), salas_path %>

app/views/salas/show.html.erb
<%= render 'maps' %>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= Sala.human_attribute_name(:nombre) %>: </strong>
  <%= @sala.nombre.capitalize %>
</p>

<p>
  <strong><%= Sala.human_attribute_name(:apellido) %>: </strong>
  <%= @sala.apellido.capitalize %>
</p>

<p>
  <strong><%= Sala.human_attribute_name(:cumple) %>: </strong>
  <%= @sala.cumple.strftime('%d/%m/%Y') %>
</p>

<p>
  <strong><%= Sala.human_attribute_name(:email) %>: </strong>
  <%= @sala.email %>
</p>

<p>
  <strong><%= Sala.human_attribute_name(:fecha_festejo) %>: </strong>
  <%= @sala.fecha_festejo.strftime('%H:%Mhrs - %d/%m/%Y') %>
</p>

<p>
  <strong><%= Sala.human_attribute_name(:lugar_festejo) %>:</strong>
  <%= @sala.lugar_festejo %>
</p>

<div style='width: 500px;'>
  <div id="map" style='width: 500px; height: 400px;'></div>
</div>

<script type="text/javascript">	
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarkers(<%=raw @hash.to_json %>);
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
      handler.getMap().setZoom(16);
	});
</script>

<br>
<%= link_to (t ".edit"), edit_sala_path(@sala) %> |
<%= link_to (t ".back"), salas_path %>

app/views/static_pages/about.es.html.erb
<h1>Acerca de Sala Verde</h1>
<p>Una aplicación web que permite a los padres de una sala de jardin de infantes
	actualizar la fecha de cumplea&ntildeos y el lugar de festejo del mismo 
	(Ruby on Rails, Geocoder, Google maps for Rails gems, Google maps V3, Bootstrap)</p>

app/views/static_pages/about.html.erb
<h1>About Sala Verde</h1>
<p>A web app that allows kindergarten parents to update their offspring’s birthdate and place where they will celebrate 
	the birthday party (Ruby on Rails, Geocoder, Google maps for Rails gems, Google maps V3, Bootstrap)</p>